[package]
name = "sdl_rust"
version = "0.1.0"
authors = ["Dominic Karras <dak198@pitt.edu>"]
edition = "2018"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf","image","mixer"]